Resolving 2.1 - 2.3
js-tasks-ru/jsbasic-20220418-2_asdfif pull request #3
Opened 2022-04-21 11:55 UTC by Asdfif

2022-04-21 11:56 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2022-04-22 14:08 UTC, SinimaWath requested changes

2022-04-22 14:08 UTC, SinimaWath commented on 2-module/1-task/index.js
> +  result = 0
Это не создание переменной. А запись в глобальны обьект.

Используй `let`

2022-04-22 14:08 UTC, SinimaWath commented on 2-module/1-task/index.js
> +    value = salaries[key]
Это не создание переменной. А запись в глобальны обьект.

Используй `let`

2022-04-22 14:08 UTC, SinimaWath commented on 2-module/1-task/index.js
> +  for (key in salaries){
Это не создание переменной. А запись в глобальны обьект.

Используй `let`

2022-04-25 07:14 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2022-04-25 18:13 UTC, SinimaWath approved these changes

2022-04-25 18:14 UTC, merged